### PR TITLE
Changes spec to match instructions

### PR DESCRIPTION
**Pull request by DakotaLMartinez**
@aturkewi 

This lab has been problematic for multiple students. The inconsistencies between the tests and the instructions are distracting from the instructional value of the lab.

### CODE REVIEW

**Comment by aturkewi** [comment]
@cjbrock @tracypholmes either of you have time to take a peak at this lab/PR?

**Comment by cjbrock** [comment]
This is actually on my list of goals for the week. I'm planning on looking at it ASAP.

**Comment by joelcowie** [comment]
@aturkewi 

Ran into this same issue with a student and solved using this approach. Curriculum still needs to be updated.

**Comment by aturkewi** [comment]
Closing this PR. I just merged in #24 and that _should_ fix. If I'm wrong though, please feel free to re-open and let me know :)

**Pull request closed without merging**
