### PR TITLE
Update hello_spec.rb

### PR DESCRIPTION
**Pull request by pickledyamsman**
After the lesson was updated a few days ago the tests no longer work for the code along. A student came up with the working tests here but I have had 1 student since then have an issue with it. These tests will pass with the code from the code along.

@aturkewi

### CODE REVIEW

**Comment by aturkewi** [comment]
@StevenNunez 
Pinging you on this because it looks like you recently updated this lesson.

**Comment by gj** [comment]
@aturkewi @StevenNunez Updating the specs per this PR fixed another student's issue today.

**Comment by DakotaLMartinez** [comment]
@aturkewi @StevenNunez @gj 
The solution branch of this repo has a different spec in it that also works:

```
require "spec_helper"

describe "#hello_t" do 
  it "takes in an argument of an array and puts out a greeting to each person in the array whose name begins with the letter T" do 
    array = ["Tim", "Tom", "Jim"]
    expect{hello_t(array){|name| puts "Hi, #{name}" if name.start_with?('T') }}.to output("Hi, Tim\nHi, Tom\n").to_stdout
    expect(hello_t(array) {|name| puts "Hi, #{name}" if name.start_with?('T') }).to eq(array)
  end
end
```

This pull request would also fix the issue.

**Comment by bhollan** [comment]
Had another student hit this issue tonight.  This should be merged.

@aturkewi

**Comment by bhollan** [comment]
Had another student run into this today.

@aturkewi

**Comment by aturkewi** [comment]
@cjbrock do you still think you might have some time to take a peak at this one?

**Comment by aturkewi** [comment]
@cjbrock I'm just gonna merge this one in. If it's not the change you were hoping to make, it should be easy enough to rollback :)

**Pull request merged**
